spring:
  application:
    name: swagger-api-docx
  profiles:
    active: local

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs/swagger-api-docx
        name: swagger-api-docx
        display-name: Swagger REST API Documentation

      - url: /v3/api-docs/ping
        name: ping
        display-name: Ping REST API Documentation

      - url: /v3/api-docs/users
        name: users
        display-name: Users REST API Documentation